### ISSUE TITLE
An unhandled exception occurred: readConfiguration is not a function

### ISSUE THREAD

**Issue by micrem73** [google/centaur#1]
Hi,
"ng serve" did not output anything. I tried several uninstall and reinstalling libraries, at least I get this error:

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
An unhandled exception occurred: readConfiguration is not a function
See "/private/var/folders/0_/97m79v9s7333j0461kw94x7c0000gn/T/ng-o6EPg2/angular-errors.log" for further details.

here is my local settings:

Angular CLI: 15.1.3
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 15.1.2
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1501.3
@angular-devkit/build-angular       15.1.3
@angular-devkit/core                15.1.3
@angular-devkit/schematics          15.1.3
@angular/animations                 9.1.7
@angular/cdk                        9.2.3
@angular/cli                        15.1.3
@angular/common                     9.1.7
@angular/compiler                   9.1.7
@angular/compiler-cli               9.1.7
@angular/fire                       6.0.0
@angular/forms                      9.1.7
@angular/material                   9.2.3
@angular/platform-browser           9.1.7
@angular/platform-browser-dynamic   9.1.7
@angular/router                     9.1.7
@schematics/angular                 15.1.3
rxjs                                6.5.5
typescript                          3.8.3

Do you have any ideas what to do to fix?

**Comment by chonger** [comment]
it looks like an angular version issue.  googling it suggests that "ng
update @angular/compiler-cli --force" is the tonic for your ailment.  bonne
chance

**Comment by micrem73** [comment]
Thanks. I solved redownloading the code and restarting from a clean one. I forced some updates that changed angular version.
